# Generated by Django 2.1.4 on 2018-12-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20181018_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionmodel',
            name='suggestion',
            field=models.URLField(max_length=240),
        ),
    ]
